# These data options are over-ridden when calling run-model.py but are expected by ModelConfig
data:
  name: "MLR" # Model version
  case_path: "data/test/prepared_cases.tsv"
  seq_path: "results/h1n1pdm_2024-02/variant_seq_counts_subyr_subloc.tsv"
  aggregation_frequency: "7D"

settings:
  fit: true # Fit the model?
  save: true # Save model state?
  load: false # Load old model?
  export_json: true  # Export model results as json
  ps: [0.5, 0.8, 0.95] # HPDI intervals to be exported

model:
  forecast_L: 52
  pool_scale: 0.25 # between 0.1 to 0.5
  generation_time: 0.39 # 2.7 days from from Lessler et al. 2011 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2937282/). Divide generation time in days by the number of days in the aggregation frequency above for proper GA calculations.
  pivot: "C.1.9.3"
  location_ga_inclusion_threshold: 10
  hierarchical: true # Keep hierarchical for analysis across regions
  version: "MLR"
  xi_prior: 0.5
  xi_by_group: false

inference:
  method: "NUTS"
  iters: 50000 # Number of iterations for SVI
  lr: 4e-4 # Learning rate for the model
  num_warmup: 200
  num_samples: 200
