data:
  gisaid:
    h3n2:
      s3_metadata: "s3://nextstrain-data-private/files/workflows/seasonal-flu/h3n2/metadata.tsv.xz"
    h1n1pdm:
      s3_metadata: "s3://nextstrain-data-private/files/workflows/seasonal-flu/h1n1pdm/metadata.tsv.xz"
    vic:
      s3_metadata: "s3://nextstrain-data-private/files/workflows/seasonal-flu/vic/metadata.tsv.xz"

data_provenances:
  - gisaid

variant_classifications:
  - subclade
  - emerging_haplotype
  - aa_haplotype

# Define mapping of forecast model's variant classification (the name that
# appears in the web interface and data file paths) and the column in the
# metadata with the corresponding variant labels.
variant_column_by_variant_classification:
  subclade: subclade_nextclade_ha
  emerging_haplotype: emerging_haplotype_ha
  aa_haplotype: subclade_haplotype_ha

lineages:
  - h1n1pdm
  - h3n2
  - vic

geo_resolutions:
  - country
  - region

min_date: "6M"
max_date: "0D"

prepare_data:
  gisaid:
    subclade:
      country:
        location_min_seq: 100
        clade_min_seq: 30
      region:
        location_min_seq: 100
        clade_min_seq: 30
    emerging_haplotype:
      country:
        location_min_seq: 100
        clade_min_seq: 30
      region:
        location_min_seq: 100
        clade_min_seq: 30
    aa_haplotype:
      country:
        location_min_seq: 100
        clade_min_seq: 50
      region:
        location_min_seq: 100
        clade_min_seq: 50
