name: Run models

on:
  workflow_dispatch:
    inputs:
      dockerImage:
        description: "Specific container image to use for build (will override the default of `nextstrain build`)"
        required: false
        type: string

jobs:
  run_models:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: aws-batch
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.dockerImage }}
      run: |
        nextstrain build \
          --aws-batch \
          --detach \
          --no-download \
          --cpus 8 \
          --memory 16GiB \
          --env AWS_DEFAULT_REGION \
          --env GITHUB_RUN_ID \
          . \
            --configfile config/defaults.yaml config/optional.yaml \
            --keep-going
      env: |
        GITHUB_RUN_ID: ${{ github.run_id }}
